# Generated by Django 5.2.9 on 2025-12-18 11:46

from django.db import migrations, models


def migrate_legacy_data_to_json(apps, schema_editor):
    """Переносим данные из старых полей в новый JSON формат"""
    ContentElement = apps.get_model('courses', 'ContentElement')

    for element in ContentElement.objects.all():
        data = {"version": 1, "type": element.content_type}

        if element.content_type == 'text':
            data["html"] = element.text_content or ""

        elif element.content_type == 'image':
            if element.image:
                data["url"] = element.image.url
                data["alt"] = element.title or ""
                data["caption"] = ""

        elif element.content_type == 'link':
            data["url"] = element.link_url or ""
            data["text"] = element.link_text or ""
            data["open_in_new_tab"] = True

        elif element.content_type == 'homework':
            data["description"] = element.homework_description or ""
            data["deadline"] = None
            data["max_file_size_mb"] = 10
            data["allowed_extensions"] = ["pdf", "docx", "zip"]

        element.data = data
        element.save(update_fields=['data'])


def reverse_migration(apps, schema_editor):
    """Обратная миграция: восстанавливаем данные из JSON в старые поля"""
    ContentElement = apps.get_model('courses', 'ContentElement')

    for element in ContentElement.objects.all():
        if not element.data:
            continue

        data = element.data
        content_type = data.get('type', element.content_type)

        if content_type == 'text':
            element.text_content = data.get('html', '')

        elif content_type == 'link':
            element.link_url = data.get('url', '')
            element.link_text = data.get('text', '')

        elif content_type == 'homework':
            element.homework_description = data.get('description', '')

        # Для image обратная миграция не нужна, т.к. файл остался на месте

        element.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_subscriptions_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentelement',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные блока'),
        ),
        migrations.AlterField(
            model_name='contentelement',
            name='content_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('video', 'Видео'), ('link', 'Ссылка'), ('homework', 'Форма для ДЗ')], max_length=20, verbose_name='Тип контента'),
        ),
        migrations.RunPython(migrate_legacy_data_to_json, reverse_migration),
    ]
