# Generated by Django 5.2.9 on 2025-12-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_contentelement_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 800x200 px (4:1). Используется в карточках курсов', null=True, upload_to='courses/thumbnails/', verbose_name='Миниатюра (превью)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 1200x400 px (3:1). Используется на странице курса', null=True, upload_to='courses/images/', verbose_name='Изображение обложки'),
        ),
    ]
