# Generated by Django 5.2.9 on 2025-12-19 12:51

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_thumbnail_alter_course_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка')),
                ('teacher_comment', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Комментарий')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проверки')),
            ],
            options={
                'verbose_name': 'История проверки ДЗ',
                'verbose_name_plural': 'История проверок ДЗ',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Оценка от 0 до 100 баллов', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='teacher_comment',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Комментарий преподавателя'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['element', 'status'], name='courses_hom_element_b87db5_idx'),
        ),
        migrations.AddField(
            model_name='homeworkreviewhistory',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='homeworkreviewhistory',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='courses.homeworksubmission', verbose_name='Домашнее задание'),
        ),
    ]
