# Generated by Django 5.2.9 on 2025-12-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_homework_grading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Отправлено'), ('reviewed', 'Проверено'), ('revision_requested', 'Требует доработки')], default='submitted', max_length=20, verbose_name='Статус'),
        ),
    ]
