# Generated by Django 5.2.9 on 2025-12-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_add_revision_requested_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentelement',
            name='publish_datetime',
            field=models.DateTimeField(blank=True, help_text='Если указано, элемент будет заблокирован до этой даты/времени (UTC)', null=True, verbose_name='Дата и время публикации'),
        ),
        migrations.AddField(
            model_name='section',
            name='publish_datetime',
            field=models.DateTimeField(blank=True, help_text='Если указано, раздел будет заблокирован до этой даты/времени (UTC)', null=True, verbose_name='Дата и время публикации'),
        ),
        migrations.AddIndex(
            model_name='contentelement',
            index=models.Index(fields=['publish_datetime'], name='courses_con_publish_ed3e66_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['publish_datetime'], name='courses_sec_publish_cdf1fd_idx'),
        ),
    ]
