# Generated by Django 5.2.9 on 2025-12-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list, help_text='Структурированный контент в формате блоков', verbose_name='Блоки контента'),
        ),
    ]
