# Generated by Django 5.2.9 on 2026-02-15 09:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Поддерживаемые форматы: jpg, jpeg, png, gif, webp. Максимум 5 МБ', upload_to='news/gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения в галерее (меньшее значение = раньше)', verbose_name='Порядок')),
                ('caption', models.CharField(blank=True, help_text='Необязательная подпись к изображению', max_length=255, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Изображения галереи',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['news', 'order'], name='news_newsim_news_id_9272f9_idx')],
            },
        ),
    ]
